In [1]:
import pandas as pd

# ✅ Load CSV (using forward slashes so no escape sequence issues)
matches = pd.read_csv("IPL Dataset/matches.csv")
deliveries = pd.read_csv("IPL Dataset/deliveries.csv")

# ✅ Make sure all columns show in one line (no wrapping with \)
pd.set_option("display.max_columns", 600)
pd.set_option("display.width", 600)

matches.head(1)  # Display the first few rows of the DataFrame

   id    Season       city        date                team1                        team2                  toss_winner toss_decision  result  dl_applied               winner  win_by_runs  win_by_wickets player_of_match                                      venue      umpire1   umpire2 umpire3
0   1  IPL-2017  Hyderabad  05-04-2017  Sunrisers Hyderabad  Royal Challengers Bangalore  Royal Challengers Bangalore         field  normal           0  Sunrisers Hyderabad           35               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal  AY Dandekar  NJ Llong     NaN

In [ ]:
print("Total Seasons:", matches['Season'].nunique())
print("Seasons:", matches['Season'].unique())

In [ ]:
matches['Season'].value_counts().sort_index()

In [ ]:

matches['venue'].value_counts().head(5)

In [ ]:
matches['toss_winner'].value_counts().head(1)

In [ ]:
matches['winner'].value_counts().head(1)

In [ ]:
matches['player_of_match'].value_counts().head(5)

In [ ]:
top_batsman = deliveries.groupby('batsman')['batsman_runs'].sum().reset_index()
display(top_batsman.sort_values(by='batsman_runs', ascending=False).head(5))

In [8]:
dhoni_runs = deliveries.query("batsman == 'MS Dhoni'")['batsman_runs'].sum()
print(f"Total runs scored by MS Dhoni: {dhoni_runs}")

Total runs scored by MS Dhoni: 4477

In [10]:
rohit_sharma_ball_faced =deliveries.query("batsman =='RG Sharma'").shape[0]
print(f"Total balls faced by Rohit Sharma: {rohit_sharma_ball_faced}")

Total balls faced by Rohit Sharma: 3816

In [14]:
gayle_sixes = deliveries.query("batsman == 'CH Gayle' and batsman_runs == 6").shape[0]
print(f"Total sixes hit by Chris Gayle: {gayle_sixes}")

Total sixes hit by Chris Gayle: 327

In [ ]:
most_balls = deliveries['bowler'].value_counts().head()
print("Most balls bowled by a bowler:")
print(most_balls)

In [ ]:
boundaries = deliveries.query("batsman_runs == 4 or batsman_runs == 6")['batsman'].value_counts().head(1)
display(boundaries)

In [36]:
valid = deliveries.query("dismissal_kind != 'run out'").groupby('bowler')['dismissal_kind'].count().reset_index(name='wickets')
display(valid.sort_values(by='wickets', ascending=False).head(5))

              bowler  wickets
340       SL Malinga      170
7           A Mishra      156
126  Harbhajan Singh      150
264        PP Chawla      149
93          DJ Bravo      147